-- ============================================================================
-- SIPPA Database Schema
-- Sistem Informasi Pemetaan Produksi Pertanian
-- Generated: 2026-09-05
-- ============================================================================

-- Drop tables if exists (reverse order of dependencies)
DROP TABLE IF EXISTS `province_padi_monthly_productions`;
DROP TABLE IF EXISTS `province_commodity_productions`;
DROP TABLE IF EXISTS `cluster_commodity_profiles`;
DROP TABLE IF EXISTS `provinces`;
DROP TABLE IF EXISTS `pca_variances`;
DROP TABLE IF EXISTS `kmeans_evaluations`;
DROP TABLE IF EXISTS `clusters`;
DROP TABLE IF EXISTS `commodities`;

-- ============================================================================
-- Table: commodities
-- Daftar komoditas pertanian (55 komoditas)
-- ============================================================================
CREATE TABLE `commodities` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `slug` VARCHAR(100) NOT NULL UNIQUE COMMENT 'Slug: padi, jagung, alpukat, dll.',
  `display_name` VARCHAR(100) NOT NULL COMMENT 'Nama tampilan: Padi, Jagung, Alpukat',
  `category` VARCHAR(50) NOT NULL COMMENT 'Kategori: pangan, buah-tahunan, sayuran-semusim, jamur',
  `reference_year` SMALLINT NOT NULL COMMENT 'Tahun data: 2024 atau 2025',
  `unit` VARCHAR(20) NOT NULL DEFAULT 'ton' COMMENT 'Satuan: ton, ha, ku/ha',
  `has_luas_panen_produktivitas` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'TRUE untuk padi & jagung',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_commodities_category` (`category`),
  INDEX `idx_commodities_year` (`reference_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: clusters
-- Hasil K-Means clustering (K=4)
-- ============================================================================
CREATE TABLE `clusters` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `cluster_number` TINYINT UNSIGNED NOT NULL UNIQUE COMMENT 'Nomor cluster: 0, 1, 2, 3',
  `name` VARCHAR(150) NOT NULL COMMENT 'Nama cluster dari cluster_name',
  `jumlah_provinsi` SMALLINT UNSIGNED NOT NULL COMMENT 'Jumlah anggota cluster',
  `karakteristik` TEXT NOT NULL COMMENT 'Ringkasan karakteristik produksi',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_clusters_number` (`cluster_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: provinces
-- Daftar 38 provinsi di Indonesia
-- ============================================================================
CREATE TABLE `provinces` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `name` VARCHAR(100) NOT NULL UNIQUE COMMENT 'Nama provinsi',
  `cluster_id` CHAR(36) NOT NULL COMMENT 'Relasi ke clusters.id',
  `geo_alias` VARCHAR(100) NULL COMMENT 'Alias nama untuk GeoJSON mapping',
  `total_production` DECIMAL(15,2) NULL COMMENT 'Total produksi semua komoditas (ton)',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT `fk_provinces_cluster` FOREIGN KEY (`cluster_id`) REFERENCES `clusters`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  INDEX `idx_provinces_cluster` (`cluster_id`),
  INDEX `idx_provinces_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: kmeans_evaluations
-- Evaluasi model K-Means untuk K=2 sampai K=8
-- ============================================================================
CREATE TABLE `kmeans_evaluations` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `k` TINYINT UNSIGNED NOT NULL UNIQUE COMMENT 'Jumlah cluster (2-8)',
  `inertia` DECIMAL(20,10) NOT NULL COMMENT 'Dipakai pada elbow method',
  `silhouette_score` DECIMAL(10,8) NOT NULL COMMENT 'Semakin tinggi semakin baik',
  `davies_bouldin_index` DECIMAL(10,8) NOT NULL COMMENT 'Semakin rendah semakin baik',
  `smallest_cluster` TINYINT UNSIGNED NOT NULL COMMENT 'Jumlah anggota cluster terkecil',
  `largest_cluster` TINYINT UNSIGNED NOT NULL COMMENT 'Jumlah anggota cluster terbesar',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_kmeans_k` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: pca_variances
-- Principal Component Analysis variance explained
-- ============================================================================
CREATE TABLE `pca_variances` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `component` TINYINT UNSIGNED NOT NULL UNIQUE COMMENT 'Nomor principal component (1-38)',
  `explained_variance` DECIMAL(12,10) NOT NULL COMMENT 'Proporsi variasi yang dijelaskan',
  `cumulative_variance` DECIMAL(12,10) NOT NULL COMMENT 'Total variasi kumulatif',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_pca_component` (`component`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: cluster_commodity_profiles
-- Profil komoditas per cluster (median & z-score)
-- ============================================================================
CREATE TABLE `cluster_commodity_profiles` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `cluster_id` CHAR(36) NOT NULL COMMENT 'Relasi ke clusters.id',
  `commodity_id` CHAR(36) NOT NULL COMMENT 'Relasi ke commodities.id',
  `median_produksi` DECIMAL(15,3) NOT NULL COMMENT 'Median produksi aktual se-cluster (ton)',
  `mean_z_score` DECIMAL(15,10) NOT NULL COMMENT 'Lebih dari 0 berarti di atas rata-rata',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT `fk_cluster_profiles_cluster` FOREIGN KEY (`cluster_id`) REFERENCES `clusters`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cluster_profiles_commodity` FOREIGN KEY (`commodity_id`) REFERENCES `commodities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY `uk_cluster_commodity_profile` (`cluster_id`, `commodity_id`),
  INDEX `idx_cluster_profiles_cluster` (`cluster_id`),
  INDEX `idx_cluster_profiles_commodity` (`commodity_id`),
  INDEX `idx_cluster_profiles_zscore` (`mean_z_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: province_commodity_productions
-- Produksi komoditas per provinsi (data utama)
-- ============================================================================
CREATE TABLE `province_commodity_productions` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `province_id` CHAR(36) NOT NULL COMMENT 'Relasi ke provinces.id',
  `commodity_id` CHAR(36) NOT NULL COMMENT 'Relasi ke commodities.id',
  `produksi` DECIMAL(15,3) NOT NULL COMMENT 'Produksi aktual (ton)',
  `luas_panen` DECIMAL(15,3) NULL COMMENT 'Luas panen (ha) - hanya untuk padi & jagung',
  `produktivitas` DECIMAL(10,3) NULL COMMENT 'Produktivitas (ku/ha) - hanya untuk padi & jagung',
  `median_cluster` DECIMAL(15,3) NOT NULL COMMENT 'Median produksi komoditas dalam cluster yang sama',
  `selisih_dengan_median_cluster` DECIMAL(15,3) NOT NULL COMMENT 'Produksi dikurangi median cluster',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT `fk_province_productions_province` FOREIGN KEY (`province_id`) REFERENCES `provinces`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_province_productions_commodity` FOREIGN KEY (`commodity_id`) REFERENCES `commodities`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY `uk_province_commodity` (`province_id`, `commodity_id`),
  INDEX `idx_province_productions_province` (`province_id`),
  INDEX `idx_province_productions_commodity` (`commodity_id`),
  INDEX `idx_province_productions_produksi` (`produksi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Table: province_padi_monthly_productions
-- Produksi padi bulanan per provinsi (data temporal)
-- ============================================================================
CREATE TABLE `province_padi_monthly_productions` (
  `id` CHAR(36) NOT NULL PRIMARY KEY COMMENT 'UUID generated by Laravel',
  `province_id` CHAR(36) NOT NULL COMMENT 'Relasi ke provinces.id',
  `month` TINYINT UNSIGNED NOT NULL COMMENT 'Bulan (1-12)',
  `year` SMALLINT UNSIGNED NOT NULL COMMENT 'Tahun data',
  `luas_panen` DECIMAL(15,3) NOT NULL COMMENT 'Luas panen (ha)',
  `produksi` DECIMAL(15,3) NOT NULL COMMENT 'Produksi (ton)',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT `fk_padi_monthly_province` FOREIGN KEY (`province_id`) REFERENCES `provinces`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY `uk_province_month_year` (`province_id`, `month`, `year`),
  INDEX `idx_padi_monthly_province` (`province_id`),
  INDEX `idx_padi_monthly_year` (`year`),
  INDEX `idx_padi_monthly_month` (`month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- End of Schema
-- ============================================================================
